live_config_reload = true

# Colors section of "Alacritty - TOML configuration file format"
# https://github.com/alacritty/alacritty/blob/master/extra/man/alacritty.5.scd#colors

import = [
    "~/.config/alacritty/colorschemes/rosepine.toml",
]

[env]
  TERM = "xterm-256color"

[cursor]
blink_interval = 550
unfocused_hollow = false

[cursor.style]
blinking = "On"
shape = "Block"

[font]
size = 9.5

[font.normal]
family="JetBrains Mono NL"
style = "Regular"

[selection]
save_to_clipboard = false

[window]
decorations = "none"
dynamic_title = true
opacity = 0.9

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 6
y = 6
